apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-helloworld
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: python-helloworld
              image: shaikhamann/cloudethix_cronjob_aman:v1
              command: ["/app/helloworld.py"]
          restartPolicy: OnFailure
