apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-01
  labels:
    app: myapp
spec:
  nodeSelector:
    cloudethix-k8s-01: worker-1
  containers:
    - name: myapp-container
      image: busybox
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']