apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-00
  labels:
    app: myapp
spec:
  nodeSelector:
    cloudethix-k8s-00: worker-0
  containers:
    - name: myapp-container
      image: busybox
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']